version: '3'

services:
  mongodb:
    image: mongo:latest
    container_name: checked-mongodb
    ports:
      - "27017:27017"
    volumes:
      - checked-mongo-data:/data/db
    networks:
      - checked-network

  backend:
    build: 
      context: ./backend
    container_name: checked-backend
    depends_on:
      - mongodb
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongodb:27017/checked_app
    networks:
      - checked-network

networks:
  checked-network:
    driver: bridge

volumes:
  checked-mongo-data:
    driver: local
    driver_opts:
      type: none
      device: /path/to/your/local/mongo/data
      o: bind